spring:
  profiles:
    active: dev
---
server:
  port: 6501

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  profiles:
    active: dev
  application:
    name: mycloud-config-client
---
server:
  port: 6502

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  profiles:
    active: test
  application:
    name: mycloud-config-client